routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::group(['namespace' => 'Front', 'prefix'=>'client', 'middleware' => ['auth:client-web'] ], function ()
// {
//   Route::get('/', 'MainController@home')->name('client-home');
//
//
//   Route::get('login', 'AuthController@login')->name('client-login');
//   Route::get('register', 'AuthController@register')->name('client-register');
//
//   Route::get('about-us', 'MainController@aboutUs');
//
//   Route::get('post', 'MainController@post')->name('post');
//
//   Route::get('contact-us', 'MainController@contactUs');
//
//   Route::get('donator', 'MainController@donator');
//
//   Route::get('requests', 'MainController@requests');
//
//   Route::get('who-we-are', 'MainController@whoWeAre');
//
// });

Route::group(['namespace' => 'Front', 'prefix'=>'client'], function ()
{

  Route::get('/', 'MainController@home')->name('client-home');


  Route::get('login', 'AuthController@login')->name('client-login');
  Route::post('login-check', 'AuthController@loginCheck')->name('client-login-check');

  Route::get('logout', 'AuthController@logout')->name('client-logout');
  //
  //
  Route::get('register', 'AuthController@register')->name('client-register');
  Route::post('registerSave', 'AuthController@registerSave')->name('client-registerSave');

  Route::get('about-us', 'MainController@aboutUs')->name('client-about-us');

  Route::get('posts', 'MainController@posts')->name('posts');
  Route::get('post/{id}', 'MainController@post')->name('post-details');

  Route::get('donations', 'MainController@donations')->name('donations');
  Route::get('donation-details/{id}', 'MainController@donationDetails')->name('donation-details');

  Route::get('contact-us', 'MainController@contactUs')->name('client-contact-us');
  Route::post('contact-us-message', 'MainController@contactUsMessage')->name('client-contact-message');

  Route::get('profile', 'AuthController@profile')->name('client-profile');
  Route::post('update-profile', 'AuthController@updateProfile')->name('client-update-profile');

  Route::get('notification-setting', 'AuthController@notificationSetting')->name('client-notification-setting');
  Route::post('notification-setting-update', 'AuthController@notificationSettingUpdate')->name('client-notification-setting-update');

  Route::get('favourite', 'MainController@favourite')->name('client-favourite');

  Route::get('create-donation', 'MainController@createDonation')->name('client-create-donation');
  Route::post('create-donation-save', 'MainController@createDonationSave')->name('client-create-donation-save');


  // Route::get('donator', 'MainController@donator');
  //
  // Route::get('requests', 'MainController@requests');
  //
  // Route::get('who-we-are', 'MainController@whoWeAre');

});

Auth::routes();

//Admin panel
Route::group(['middleware' => ['auth'] , 'prefix'=>'admin'],function ()
{
  Route::get('/home', 'HomeController@index')->name('home');
  Route::resource('governorate','GovernorateController');
  Route::resource('city','CityController');
  Route::resource('category','CategoryController');
  Route::resource('post','PostController');
  Route::resource('client','ClientController');
  Route::get('clients-activate/{id}', 'ClientController@activate')->name('clients.activate');
  Route::get('clients-deactivate/{id}', 'ClientController@deactivate')->name('clients.deactivate');

  Route::resource('change-password','ChangePasswordController');
  Route::resource('contact','ContactController');
  Route::resource('donation','DonationController');
  Route::resource('setting','SettingController');
  Route::resource('role','RoleController');
  Route::resource('user','UserController');

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Zizaco\Entrust\Traits\EntrustUserTrait;
class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    // public function roles()
    // {
    //   return $this->belongsToMany('App\Role');
    // }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $records = User::all();

      return view('users.index',compact('records'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $rules = [
        'name' => 'required|unique:users,name',
        'password' => 'required|confirmed',
        'email' => 'required',
        'roles_list' => 'required|array',
      ];

      $messages = [
        'name.required' => 'Name is required',
        'password.required' => 'Password is required',
        'email.required' => 'Email is required',
        'roles_list.required' => 'Roles is required',
      ];

      $this->validate($request, $rules, $messages);
      $request->merge(['password' => bcrypt($request->password)]);

      $record = User::create($request->except('roles_list'));
      $record->roles()->attach($request->roles_list);

      flash()->success("تم إضافة مستخدم بنجاح");

      return redirect(route('user.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $model = User::findOrFail($id);

      return view('users.edit', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $rules = [
        'name' => 'required',
        'password' => 'required|confirmed',
        'email' => 'required',
        'roles_list' => 'required',
      ];

      $messages = [
        'name.required' => 'Name is required',
        'name.required' => 'Password is required',
        'name.required' => 'Email is required',
        'name.required' => 'Roles is required',
      ];
      $this->validate($request, $rules, $messages);

      $record = User::findOrFail($id);
      $record->roles()->sync((array)$request->roles_list);
      $request->merge(['password' => bcrypt($request->password)]);

      $record->update($request->all());
      flash()->success("تم التعديل بنجاح");
      return redirect(route('user.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $record = User::findOrFail($id);
      $record->delete();
      flash()->success("تم الحذف بنجاح");
      return back();
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')
@inject('model','App\User')
@section('page_title')
  Create User
@endsection

@section('content')


<!-- Main content -->

<section class="content">

  <!-- Default box -->
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">Create User</h3>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="card-body">

      @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
      @endif
      {!! Form::model($model,[

        'action' => 'UserController@store'

        ]) !!}

        <div class="form-group">
          <label>name</label>
          {!! Form::text('name',null,[
            'class' => 'form-control'
          ]) !!}

        </div>
        <div class="form-group">
          <label>Email</label>
          {!! Form::text('email',null,[
            'class' => 'form-control'
          ]) !!}

        </div>
        <div class="form-group">
          <label>Phone</label>
          {!! Form::text('phone',null,[
            'class' => 'form-control'
          ]) !!}

        </div>
        <div class="form-group">
          <label>password</label>
          {!! Form::password('password',[
            'class' => 'form-control'
          ]) !!}

        </div>
        <div class="form-group">
          <label>password</label>
          {!! Form::password('password_confirmation',[
            'class' => 'form-control'
          ]) !!}

        </div>
        <div class="form-group">
          @inject('role','App\Role')
          <label>Roles</label>
          {!! Form::select('roles_list[]',$role->pluck('display_name','id'),null,[
            'class' => 'form-control',
            'multiple' => 'multiple'
          ]) !!}

        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary"> Submit </button>
        </div>

        {!! Form::close() !!}
    </div>
    <!-- /.card-body -->

  </div>
  <!-- /.card -->

</section>
<!-- /.content -->


@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('page_title')
  Edit User
@endsection

@section('content')


<!-- Main content -->

<section class="content">

  <!-- Default box -->
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">Edit User</h3>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="card-body">

      @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
      @endif
      {!! Form::model($model,[

        'action' => ['UserController@update', $model->id],
        'method' => 'put'

        ]) !!}


        <div class="form-group">
          <label>name</label>
          {!! Form::text('name',null,[
            'class' => 'form-control'
          ]) !!}

        </div>
        <div class="form-group">
          <label>Email</label>
          {!! Form::text('email',null,[
            'class' => 'form-control'
          ]) !!}

        </div>
        <div class="form-group">
          <label>Phone</label>
          {!! Form::text('phone',null,[
            'class' => 'form-control'
          ]) !!}

        </div>
        <div class="form-group">
          <label>password</label>
          {!! Form::password('password',[
            'class' => 'form-control'
          ]) !!}

        </div>
        <div class="form-group">
          <label>password</label>
          {!! Form::password('password_confirmation',[
            'class' => 'form-control'
          ]) !!}

        </div>
        <div class="form-group">
          @inject('role','App\Role')
          <label>Roles</label>
          {!! Form::select('roles_list[]',$role->pluck('display_name','id'),$model->roles()->pluck('id'),[
            'class' => 'form-control',
            'multiple' => 'multiple'
          ]) !!}

        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary"> Submit </button>
        </div>

        {!! Form::close() !!}
    </div>
    <!-- /.card-body -->

  </div>
  <!-- /.card -->

</section>
<!-- /.content -->


@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('page_title')
  User
@endsection

@section('content')


<!-- Main content -->

<section class="content">

  <!-- Default box -->
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">List of Users</h3>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="card-body">
      <div><a href="{{url(route('user.create'))}}" class="btn btn-primary"><i class="fa fa-plus"></i> New User</a></div>
      <br>
      @include('flash::message')
      @if(count($records))
        <div class="table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th class="text-center">#</th>
                <th class="text-center">Name</th>
                <th class="text-center">Email</th>
                <th class="text-center">Role</th>
                <th class="text-center">Edit</th>
                <th class="text-center">Delete</th>
              </tr>
            </thead>
            <tbody>
              @foreach ($records as $record)
                <tr>
                  <td class="text-center">{{$loop->iteration}}</td>
                  <td class="text-center">{{$record->name}}</td>
                  <td class="text-center">{{$record->email}}</td>
                  <td class="text-center">
                    <ul>
                        @foreach($record->roles as $role)
                            <li>{{$role->display_name}}</li>
                        @endforeach
                    </ul>

                  </td>
                  <td class="text-center">
                    <a href="{{url(route('user.edit',$record->id))}}" class="btn btn-success btn-xs"><i class="fa fa-edit"></i></a>
                  </td>
                  <td class="text-center">
                    {!! Form::open([
                        'action' => ['UserController@destroy',$record->id],
                        'method' => 'delete'
                      ]) !!}
                      <button type="submit" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></button>
                    {!! Form::close() !!}

                  </td>
                </tr>
              @endforeach
            </tbody>

          </table>

        </div>

      @else
      <div class="alert alert-danger" role="alert">
          No Data
      </div>
      @endif

    </div>
    <!-- /.card-body -->

  </div>
  <!-- /.card -->

</section>
<!-- /.content -->


@endsection