routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::group(['namespace' => 'Front', 'prefix'=>'client', 'middleware' => ['auth:client-web'] ], function ()
// {
//   Route::get('/', 'MainController@home')->name('client-home');
//
//
//   Route::get('login', 'AuthController@login')->name('client-login');
//   Route::get('register', 'AuthController@register')->name('client-register');
//
//   Route::get('about-us', 'MainController@aboutUs');
//
//   Route::get('post', 'MainController@post')->name('post');
//
//   Route::get('contact-us', 'MainController@contactUs');
//
//   Route::get('donator', 'MainController@donator');
//
//   Route::get('requests', 'MainController@requests');
//
//   Route::get('who-we-are', 'MainController@whoWeAre');
//
// });

Route::group(['namespace' => 'Front', 'prefix'=>'client'], function ()
{

  Route::get('/', 'MainController@home')->name('client-home');


  Route::get('login', 'AuthController@login')->name('client-login');
  Route::post('login-check', 'AuthController@loginCheck')->name('client-login-check');

  Route::get('logout', 'AuthController@logout')->name('client-logout');
  //
  //
  Route::get('register', 'AuthController@register')->name('client-register');
  Route::post('registerSave', 'AuthController@registerSave')->name('client-registerSave');

  Route::get('about-us', 'MainController@aboutUs')->name('client-about-us');

  Route::get('posts', 'MainController@posts')->name('posts');
  Route::get('post/{id}', 'MainController@post')->name('post-details');

  Route::get('donations', 'MainController@donations')->name('donations');
  Route::get('donation-details/{id}', 'MainController@donationDetails')->name('donation-details');

  Route::get('contact-us', 'MainController@contactUs')->name('client-contact-us');
  Route::post('contact-us-message', 'MainController@contactUsMessage')->name('client-contact-message');

  Route::get('profile', 'AuthController@profile')->name('client-profile');
  Route::post('update-profile', 'AuthController@updateProfile')->name('client-update-profile');

  Route::get('notification-setting', 'AuthController@notificationSetting')->name('client-notification-setting');
  Route::post('notification-setting-update', 'AuthController@notificationSettingUpdate')->name('client-notification-setting-update');

  Route::get('favourite', 'MainController@favourite')->name('client-favourite');

  Route::get('create-donation', 'MainController@createDonation')->name('client-create-donation');
  Route::post('create-donation-save', 'MainController@createDonationSave')->name('client-create-donation-save');


  // Route::get('donator', 'MainController@donator');
  //
  // Route::get('requests', 'MainController@requests');
  //
  // Route::get('who-we-are', 'MainController@whoWeAre');

});

Auth::routes();

//Admin panel
Route::group(['middleware' => ['auth'] , 'prefix'=>'admin'],function ()
{
  Route::get('/home', 'HomeController@index')->name('home');
  Route::resource('governorate','GovernorateController');
  Route::resource('city','CityController');
  Route::resource('category','CategoryController');
  Route::resource('post','PostController');
  Route::resource('client','ClientController');
  Route::get('clients-activate/{id}', 'ClientController@activate')->name('clients.activate');
  Route::get('clients-deactivate/{id}', 'ClientController@deactivate')->name('clients.deactivate');

  Route::resource('change-password','ChangePasswordController');
  Route::resource('contact','ContactController');
  Route::resource('donation','DonationController');
  Route::resource('setting','SettingController');
  Route::resource('role','RoleController');
  Route::resource('user','UserController');

});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{

    protected $table = 'posts';
    public $timestamps = true;
    protected $fillable = array('title', 'image', 'content', 'category_id');

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function clients()
    {
        return $this->belongsToMany('App\Client');
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Category;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $records = Post::all();

      return view('posts.index',compact('records'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view ('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $rules = [
        'title' => 'required',
        'image' =>'required',
        'content' =>'required',
        'category_id' =>'required',
      ];

      $messages = [
        'title.required' => 'Title is required',
        'image.required' => 'Image is required',
        'content.required' => 'content is required',
        'category_id.required' => 'Category is required'
      ];

      $this->validate($request, $rules, $messages);

      $record = Post::create($request->all());

      if ($request->hasFile('image')) {
            $path = public_path();
            $destinationPath = $path . '/uploads/posts/'; // upload path
            $logo = $request->file('image');
            $extension = $logo->getClientOriginalExtension(); // getting image extension
            $name = time() . '' . rand(11111, 99999) . '.' . $extension; // renameing image
            $logo->move($destinationPath, $name); // uploading file to given path
            $record->image = 'uploads/posts/' . $name;
            $record->save();
        }

      flash()->success("تم إضافة مقال بنجاح");

      return redirect(route('post.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $model = Post::findOrFail($id);

      return view('posts.edit', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $record = Post::findOrFail($id);
      $record->update($request->all());
      flash()->success("تم التعديل بنجاح");
      return redirect(route('post.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $record = Post::findOrFail($id);
      $record->delete();
      flash()->success("تم الحذف بنجاح");
      return back();
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')
@inject('model','App\Post')
@section('page_title')
  Create Post
@endsection

@section('content')


<!-- Main content -->

<section class="content">

  <!-- Default box -->
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">Create Posts</h3>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="card-body">

      @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
      @endif
      {!! Form::model($model,[

        'action' => 'PostController@store',
        'files' => 'true'

        ]) !!}

        <div class="form-group">

          <label>title</label>
          {!! Form::text('title',null,[
            'class' => 'form-control'
          ]) !!}
        </div>

        <div class="form-group">
          <label>image</label>
          {!! Form::file('image',null,[
            'class' => 'form-control'
          ]) !!}
        </div>

        <div class="form-group">
          <label>content</label>
          {!! Form::textarea('content',null,[
            'class' => 'form-control'
          ]) !!}
        </div>

        <div class="form-group">
          @inject('categories','App\Category')
          {!! Form::Label('category', 'Category :') !!}
          {!! Form::select('category_id', $categories->pluck('name','id')->toArray(), ['class' => 'form-control']) !!}
        </div>
        <br>

        <div class="form-group">
          <button type="submit" class="btn btn-primary"> Submit </button>
        </div>

        {!! Form::close() !!}
    </div>
    <!-- /.card-body -->

  </div>
  <!-- /.card -->

</section>
<!-- /.content -->


@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')
@section('page_title')
  Edit Posts
@endsection

@section('content')


<!-- Main content -->

<section class="content">

  <!-- Default box -->
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">Edit Posts</h3>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="card-body">

      @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
      @endif

      {!! Form::model($model,[

        'action' => ['PostController@update', $model->id],
        'files' => 'true',
        'method' => 'put'


        ]) !!}

        <div class="form-group">

          <label>title</label>
          {!! Form::text('title',null,[
            'class' => 'form-control'
          ]) !!}
        </div>

        <div class="form-group">
          <label>image</label>
          {!! Form::file('image',null,[
            'class' => 'form-control'
          ]) !!}
        </div>

        <div class="form-group">
          <label>content</label>
          {!! Form::textarea('content',null,[
            'class' => 'form-control'
          ]) !!}
        </div>

        <div class="form-group">
          @inject('categories','App\Category')
          {!! Form::Label('category', 'Category :') !!}
          {!! Form::select('category_id', $categories->pluck('name','id')->toArray(), ['class' => 'form-control']) !!}
        </div>
        <br>

        <div class="form-group">
          <button type="submit" class="btn btn-primary"> Submit </button>
        </div>

        {!! Form::close() !!}
    </div>
    <!-- /.card-body -->

  </div>
  <!-- /.card -->

</section>
<!-- /.content -->


@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('page_title')
  Post
@endsection

@section('content')


<!-- Main content -->

<section class="content">

  <!-- Default box -->
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">List of Posts</h3>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="card-body">
      <a href="{{url(route('post.create'))}}" class="btn btn-primary"><i class="fa fa-plus"></i> New Post</a>
      <br>
      @include('flash::message')
      @if(count($records))
        <div class="table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th class="text-center">#</th>
                <th class="text-center">Title</th>
                <th class="text-center">Content</th>
                <th class="text-center">Image</th>
                <th class="text-center">Category</th>
                <th class="text-center">Edit</th>
                <th class="text-center">Delete</th>
              </tr>
            </thead>
            <tbody>
              @foreach ($records as $record)
                <tr>
                  <td class="text-center">{{$loop->iteration}}</td>
                  <td class="text-center">{{$record->title}}</td>
                  <td class="text-center">{{$record->content}}</td>
                  <td class="text-center"><img src="{{asset($record->image)}}" height="50px" width="50p"></td>
                  <td class="text-center">{{optional($record->category)->name}}</td>
                  <td class="text-center">
                    <a href="{{url(route('post.edit',$record->id))}}" class="btn btn-success btn-xs"><i class="fa fa-edit"></i></a>
                  </td>
                  <td class="text-center">
                    {!! Form::open([
                        'action' => ['PostController@destroy',$record->id],
                        'method' => 'delete'
                      ]) !!}
                      <button type="submit" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></button>
                    {!! Form::close() !!}

                  </td>
                </tr>
              @endforeach
            </tbody>

          </table>

        </div>

      @else
      <div class="alert alert-danger" role="alert">
          No Data
      </div>
      @endif

    </div>
    <!-- /.card-body -->

  </div>
  <!-- /.card -->

</section>
<!-- /.content -->


@endsection