routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::group(['namespace' => 'Front', 'prefix'=>'client', 'middleware' => ['auth:client-web'] ], function ()
// {
//   Route::get('/', 'MainController@home')->name('client-home');
//
//
//   Route::get('login', 'AuthController@login')->name('client-login');
//   Route::get('register', 'AuthController@register')->name('client-register');
//
//   Route::get('about-us', 'MainController@aboutUs');
//
//   Route::get('post', 'MainController@post')->name('post');
//
//   Route::get('contact-us', 'MainController@contactUs');
//
//   Route::get('donator', 'MainController@donator');
//
//   Route::get('requests', 'MainController@requests');
//
//   Route::get('who-we-are', 'MainController@whoWeAre');
//
// });

Route::group(['namespace' => 'Front', 'prefix'=>'client'], function ()
{

  Route::get('/', 'MainController@home')->name('client-home');


  Route::get('login', 'AuthController@login')->name('client-login');
  Route::post('login-check', 'AuthController@loginCheck')->name('client-login-check');

  Route::get('logout', 'AuthController@logout')->name('client-logout');
  //
  //
  Route::get('register', 'AuthController@register')->name('client-register');
  Route::post('registerSave', 'AuthController@registerSave')->name('client-registerSave');

  Route::get('about-us', 'MainController@aboutUs')->name('client-about-us');

  Route::get('posts', 'MainController@posts')->name('posts');
  Route::get('post/{id}', 'MainController@post')->name('post-details');

  Route::get('donations', 'MainController@donations')->name('donations');
  Route::get('donation-details/{id}', 'MainController@donationDetails')->name('donation-details');

  Route::get('contact-us', 'MainController@contactUs')->name('client-contact-us');
  Route::post('contact-us-message', 'MainController@contactUsMessage')->name('client-contact-message');

  Route::get('profile', 'AuthController@profile')->name('client-profile');
  Route::post('update-profile', 'AuthController@updateProfile')->name('client-update-profile');

  Route::get('notification-setting', 'AuthController@notificationSetting')->name('client-notification-setting');
  Route::post('notification-setting-update', 'AuthController@notificationSettingUpdate')->name('client-notification-setting-update');

  Route::get('favourite', 'MainController@favourite')->name('client-favourite');

  Route::get('create-donation', 'MainController@createDonation')->name('client-create-donation');
  Route::post('create-donation-save', 'MainController@createDonationSave')->name('client-create-donation-save');


  // Route::get('donator', 'MainController@donator');
  //
  // Route::get('requests', 'MainController@requests');
  //
  // Route::get('who-we-are', 'MainController@whoWeAre');

});

Auth::routes();

//Admin panel
Route::group(['middleware' => ['auth'] , 'prefix'=>'admin'],function ()
{
  Route::get('/home', 'HomeController@index')->name('home');
  Route::resource('governorate','GovernorateController');
  Route::resource('city','CityController');
  Route::resource('category','CategoryController');
  Route::resource('post','PostController');
  Route::resource('client','ClientController');
  Route::get('clients-activate/{id}', 'ClientController@activate')->name('clients.activate');
  Route::get('clients-deactivate/{id}', 'ClientController@deactivate')->name('clients.deactivate');

  Route::resource('change-password','ChangePasswordController');
  Route::resource('contact','ContactController');
  Route::resource('donation','DonationController');
  Route::resource('setting','SettingController');
  Route::resource('role','RoleController');
  Route::resource('user','UserController');

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model 
{

    protected $table = 'categories';
    public $timestamps = true;
    protected $fillable = array('name');

    public function posts()
    {
        return $this->hasMany('App\Post');
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $records = Category::all();

      return view('categories.index',compact('records'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $rules = [
        'name' => 'required'
      ];

      $messages = [
        'name.required' => 'Name is required'
      ];

      $this->validate($request, $rules, $messages);

      $record = Category::create($request->all());

      flash()->success("تم إضافة قسم بنجاح");

      return redirect(route('category.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $model = Category::findOrFail($id);

      return view('categories.edit', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $record = Category::findOrFail($id);
      $record->update($request->all());
      flash()->success("تم التعديل بنجاح");
      return redirect(route('category.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $record = Category::findOrFail($id);
      $record->delete();
      flash()->success("تم الحذف بنجاح");
      return back();
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')
@inject('model','App\Category')
@section('page_title')
  Create Category
@endsection

@section('content')


<!-- Main content -->

<section class="content">

  <!-- Default box -->
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">Create Category</h3>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="card-body">

      @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
      @endif
      {!! Form::model($model,[

        'action' => 'CategoryController@store'

        ]) !!}

        <div class="form-group">
          <label>name</label>
          {!! Form::text('name',null,[
            'class' => 'form-control'
          ]) !!}

        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary"> Submit </button>
        </div>

        {!! Form::close() !!}
    </div>
    <!-- /.card-body -->

  </div>
  <!-- /.card -->

</section>
<!-- /.content -->


@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')
@inject('$model','App\Category')
@section('page_title')
  Create Category
@endsection

@section('content')


<!-- Main content -->

<section class="content">

  <!-- Default box -->
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">Create Categories</h3>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="card-body">

      @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
      @endif
      {!! Form::model($model,[

        'action' => ['CategoryController@update', $model->id],
        'method' => 'put'

        ]) !!}

        <div class="form-group">
          <label>name</label>
          {!! Form::text('name',null,[
            'class' => 'form-control'
          ]) !!}

        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary"> Submit </button>
        </div>

        {!! Form::close() !!}
    </div>
    <!-- /.card-body -->

  </div>
  <!-- /.card -->

</section>
<!-- /.content -->


@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('page_title')
  Category
@endsection

@section('content')


<!-- Main content -->

<section class="content">

  <!-- Default box -->
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">List of Categories</h3>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="card-body">
      <div><a href="{{url(route('category.create'))}}" class="btn btn-primary"><i class="fa fa-plus"></i> New Category</a></div>
      <br>
      @include('flash::message')
      @if(count($records))
        <div class="table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th class="text-center">#</th>
                <th class="text-center">Name</th>
                <th class="text-center">Edit</th>
                <th class="text-center">Delete</th>
              </tr>
            </thead>
            <tbody>
              @foreach ($records as $record)
                <tr>
                  <td class="text-center">{{$loop->iteration}}</td>
                  <td class="text-center">{{$record->name}}</td>
                  <td class="text-center">
                    <a href="{{url(route('category.edit',$record->id))}}" class="btn btn-success btn-xs"><i class="fa fa-edit"></i></a>
                  </td>
                  <td class="text-center">
                    {!! Form::open([
                        'action' => ['CategoryController@destroy',$record->id],
                        'method' => 'delete'
                      ]) !!}
                      <button type="submit" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></button>
                    {!! Form::close() !!}

                  </td>
                </tr>
              @endforeach
            </tbody>

          </table>

        </div>

      @else
      <div class="alert alert-danger" role="alert">
          No Data
      </div>
      @endif

    </div>
    <!-- /.card-body -->

  </div>
  <!-- /.card -->

</section>
<!-- /.content -->


@endsection